version: '3.9'
services:
  db: 
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432
    env_file:
      - .env
  admin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    volumes:
    - ./admin:/var/lib/pgadmin
    ports:
      - 8080:80
    depends_on:
      - db